#!/bin/bash


export CROSS_COMPILE=../../../prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/arm-eabi-
export ARCH=arm

if [ ! -z $1 ];then
    make distclean
fi

make mx6qs606android_defconfig
#make mx6qsabresdandroid_defconfig
make
